### ISSUE TITLE
Workflow with multiple branches

### ISSUE THREAD

**Issue by vojtech-dobes** [nextras/migrations#2]
Question to any users of this library - how do you use it if you create branch per feature/bug?

My problematic scenario:
1. On Monday I create PR with migration `2016-05-02-migration.sql`.
2. On Wednesday somebody else creates PR with migration `2016-05-04-migration.sql`.
3. Because I am lame programmer, second PR gets merged first, is deployed, and migrations is run in production.
4. Few days later my PR finally gets merged too. But now, because of its name, migration library will scream.

How do you solve this issue? From my point of view it might be good thing to be able to switch off sorting of migrations, but have ability to bind few together (declare dependency on others).

**Comment by hrach** [comment]
cc @vojtech-dobes

**Comment by vojtech-dobes** [comment]
What is context of this revert?

**Comment by JanTvrdik** [comment]
Order in which migrations are executed does matter and it is important that Nextras\Migrations by default guarantee that this order does not change because without this guarantee the migrations may randomly fail or you may loose some data on production.

**Comment by vojtech-dobes** [comment]
I understand that, but why does it get reverted now? How is problem described in this issue solved differently now?

**Comment by JanTvrdik** [comment]
> why does it get reverted now?

Because I came back!

> How is problem described in this issue solved differently now?

It is not solved because it is (technically) not an issue but a feature. The current behavior is intentional. We may consider introducing some options such `--force` to ignore all errors or `--weak-order` to ignore this specific error but the default behavior must provide the strong order guarantee.

**Comment by dakorpar** [comment]
@JanTvrdik @vojtech-dobes is anything like this introduced? I'm aware of risk but working in team and using it like this is almost impossible. It often happens that migrations fails because later migration is executed after first one. Maybe adding something more to name so it's dependant on other only if same name is there? for instance table-name-YYYY-mm-dd-nnn-description
