### ISSUE TITLE
BC break in file checkum in 3.0

### ISSUE THREAD

**Issue by hrach** [nextras/migrations#50]
> zdravim, delam neco spatne nebo se opravdu pri prechodu v nextras/migrations z verze 2.3.1 na ^3.0 menil vypocet checksumu souboru? po staru koukam: `$file->checksum = md5_file($group->directory . '/' . $file->name);`
> po novu: `md5(str_replace(["\r\n", "\r"], "\n", $content));` takze par hashu mi tim padem nesedi...resp. par sedi, zbytek je v hajzlu :worried: budu muset ten str_replace v src vyhodit asi..nevim ale jak je to pak s composer update? nebude to porad prepisovat?

**Comment by JanTvrdik** [comment]
And the point is? This was an [intentional change](https://github.com/nextras/migrations/commit/df689da2bd5bab476b5654dea2c9bc899f655355) because A LOT of people use `core.autocrlf = true` in Git which resulted in different hashes on production and on localhost. 

The correct fix is not to change source code but update the hashes (basically running migrations on localhost & copy pasting the migrations table should to the trick).

**Comment by hrach** [comment]
The point is, that the new way calculates the hash differently. So after deploying the updated code into production the migrations may fail. 

This should have been mentioned in release notes & the best way of fixing it should be also mentioned.  But I see we didn't release proper release notes 😕

**Comment by hrach** [comment]
Oh, I missed it, 3.1 is wip, not the 3.0 release notes.
